### ISSUE TITLE
auto generate hash

### ISSUE THREAD

**Issue by ghost1372** [ptorr-msft/WinGetYamlGenerator#20]
Hi, if you have a plan to generate hash for url, I can submit a PR. I have already done this for my own [HandyWinget-Gui](https://github.com/handyorg/handywinget-gui)

**Comment by ghost1372** [comment]
Sorry i didnt see your hash generator

**Comment by ptorr-msft** [comment]
Cool, and thanks for the offer! I explicitly avoided doing the auto-download feature since it requires the app to have network connectivity, and that was something I was reluctant to add (privacy concerns, etc.). Maybe I'm weird, but I find it comforting that nobody has to worry about the app doing anything nefarious :). 

Hence the "shell out to the browser then pick the file" approach. I agree the UX is not very slick. 

Feel free to add a PR to the README with your alternate repo.

**Comment by ptorr-msft** [comment]
...maybe add a section "Other related projects" and link to yours.
